
[[main]]
  identifier = "concepts"
  name = "concepts"
  url = "concepts"
  weight = 1
    
[[main]]
  identifier = "resources"
  name = "resources"
  url = "resources"
  weight = 3
    
[[main]]
  parent = "resources"
  name = "tests"
  url = "resources/tests"

[[main]]
  parent = "resources"
  name = "blogs"
  url = "resources/blogs"

[[main]]
parent = "resources"
name = "videos"
url = "resources/videos"

[[main]]
parent = "resources"
name = "papers"
url = "resources/papers"

[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 1


